### ISSUE TITLE
'utf-8' codec can't decode byte 0xa3 in position 0: invalid start byte

### ISSUE THREAD

**Issue by Wud1** [FuYanzhe2/Name-Entity-Recognition#18]
Traceback (most recent call last):
  File "C:/Users/Chenxinliang/Desktop/Name-Entity-Recognition-master/Chinese_ner/main.py", line 231, in <module>
    if __name__ == "__main__":
  File "C:\Users\Chenxinliang\Desktop\BERT-NER_3.0_test\venv\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "C:/Users/Chenxinliang/Desktop/Name-Entity-Recognition-master/Chinese_ner/main.py", line 225, in main
    clean(FLAGS)
  File "C:/Users/Chenxinliang/Desktop/Name-Entity-Recognition-master/Chinese_ner/main.py", line 191, in train
    
  File "C:/Users/Chenxinliang/Desktop/Name-Entity-Recognition-master/Chinese_ner/main.py", line 88, in evaluate
    # print(ner_results)
  File "C:\Users\Chenxinliang\Desktop\Name-Entity-Recognition-master\Chinese_ner\utils.py", line 69, in test_ner
    eval_lines = return_report(output_file)
  File "C:\Users\Chenxinliang\Desktop\Name-Entity-Recognition-master\Chinese_ner\conlleval.py", line 282, in return_report
    counts = evaluate(f)
  File "C:\Users\Chenxinliang\Desktop\Name-Entity-Recognition-master\Chinese_ner\conlleval.py", line 74, in evaluate
    for line in iterable:
  File "C:\Users\Chenxinliang\AppData\Local\Programs\Python\Python36\lib\codecs.py", line 711, in __next__
    return next(self.reader)
  File "C:\Users\Chenxinliang\AppData\Local\Programs\Python\Python36\lib\codecs.py", line 642, in __next__
    line = self.readline()
  File "C:\Users\Chenxinliang\AppData\Local\Programs\Python\Python36\lib\codecs.py", line 555, in readline
    data = self.read(readsize, firstline=True)
  File "C:\Users\Chenxinliang\AppData\Local\Programs\Python\Python36\lib\codecs.py", line 501, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 0: invalid start byte

您好，运行您的chinese_ner 出现这种错误，请问怎么解决呢？

**Comment by sunshine16817** [comment]
您好，请问您解决了吗？谢谢
